- name: Bootstrap dotfile setup
  hosts: localhost
  
  roles:
    - essentials
    - zsh
    # - git
    - flathub
    - keyd
    - role: dotfiles
      vars:
        config_dirs:
          - nvim
          - kitty
          - hypr
          - waybar
          - rofi
