- name: Check if /etc/keyd exists
  ansible.builtin.stat:
    path: /etc/keyd
  register: key_dir

- name: Install keyd keyboard mapper from source
  become: yes
  shell: |
    cd /tmp
    git clone https://github.com/rvaiya/keyd
    cd keyd
    make && sudo make install
    sudo systemctl enable keyd --now
  when: not (key_dir.stat.exists and key_dir.stat.isdir)

- name: Copy keyd config
  become: yes
  shell: |
    sudo cp ../../../config/keyd/default.conf /etc/default/keyd/
    sudo systemctl restart keyd
  when: key_dir.stat.exists and key_dir.stat.isdir

